version: '2'
services:
  apache:
    container_name: apache
    build: ./apache
    ports:
      - '80:80'
    volumes:
      - './www:/var/www/html'
      - './mail:/var/mail'
      - './apache/000-default.conf:/etc/apache2/sites-available/000-default.conf'
    environment:
      - TZ=Europe/Moscow

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bitrix
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Moscow
    ports:
      - '8080:8080'